background = #fefefe
foreground = #1e1e1e
cursor-color = #000080
selection-background = #000080
selection-foreground = #fefefe

palette = 0=#000000
palette = 1=#800000
palette = 2=#008000
palette = 3=#808000
palette = 4=#000080
palette = 5=#800080
palette = 6=#008080
palette = 7=#c0c0c0

palette = 8=#808080
palette = 9=#ff0000
palette = 10=#00ff00
palette = 11=#ffff00
palette = 12=#0000ff
palette = 13=#ff00ff
palette = 14=#00ffff
palette = 15=#ffffff
