background = #fefefe
foreground = #1e1e1e
cursor-color = #1e1e1e
selection-background = #d45bb6
selection-foreground = #fefefe

palette = 0=#1e1e1e
palette = 1=#c45c78
palette = 2=#03aa5c
palette = 3=#c9a227
palette = 4=#000080
palette = 5=#d45bb6
palette = 6=#09aea1
palette = 7=#c0c0c0

palette = 8=#858585
palette = 9=#f386a1
palette = 10=#14c46e
palette = 11=#e0c04a
palette = 12=#1e1e9a
palette = 13=#e070c4
palette = 14=#1bc4b6
palette = 15=#1e1e1e
